# Generated by Django 5.2.14 on 2026-07-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('thrill', 'thrill'), ('family', 'family'), ('kids', 'kids'), ('water', 'water'), ('vr', 'vr')], max_length=20)),
                ('thrill_level', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('min_height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('open', 'open'), ('busy', 'busy'), ('maintenance', 'maintenance'), ('closed', 'closed')], default='open', max_length=20)),
                ('queue_enabled', models.BooleanField(default=True)),
                ('max_queue_size', models.PositiveIntegerField(default=200)),
                ('img', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked', models.PositiveIntegerField(default=0)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='virtual_queue.ride')),
            ],
        ),
        migrations.CreateModel(
            name='UserQueueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('total_wait_min', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'In queue, waiting for turn'), ('boarding', "It's their turn, at ride entrance"), ('completed', 'Successfully rode the ride'), ('cancelled', 'User left queue / no-show')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait', models.PositiveIntegerField()),
                ('boarding_time', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='virtual_queue.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
