# Generated by Django 5.2.14 on 2026-07-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0003_offer_booking_invoice_promocode_bookingpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cuisine', models.CharField(max_length=50)),
                ('tagline', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('bg', models.CharField(max_length=7)),
                ('img', models.URLField(blank=True, max_length=500, null=True)),
                ('menu_img', models.URLField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('opening_time', models.TimeField(default='10:00:00')),
                ('closing_time', models.TimeField(default='22:00:00')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Under Maintenance')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_price', models.PositiveIntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('seasonal_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_ticket',
            field=models.CharField(blank=True, default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ride',
            name='closing_time',
            field=models.TimeField(default='21:00:00'),
        ),
        migrations.AddField(
            model_name='ride',
            name='expected_reopening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='maintenance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ride',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='ride',
            name='safety_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='virtual_queue.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='virtual_queue.restaurant')),
            ],
        ),
    ]
