# Generated by Django 5.2.14 on 2026-07-28 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0004_restaurant_systemconfig_tickettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_batch_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_cycle_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_phase',
            field=models.CharField(default='boarding', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='ride',
            name='loading_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='virtualqueue',
            name='batch_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
