# Generated by Django 5.2.14 on 2026-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0005_ride_current_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualqueue',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
