# Generated by Django 5.2.14 on 2026-07-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0006_virtualqueue_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('tag', models.CharField(default='CROWD_ALERT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='virtualqueue',
            name='xp_earned',
        ),
        migrations.AlterField(
            model_name='offer',
            name='adult_price',
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='child_price',
            field=models.PositiveIntegerField(default=699),
        ),
        migrations.AlterField(
            model_name='offer',
            name='senior_price',
            field=models.PositiveIntegerField(default=799),
        ),
    ]
