import { RideCategory, ThrillLevel } from '../../../types';
import nitroImg from '@/assets/nitro.jpg';
import screamImg from '@/assets/scream_machine.jpg';
import dropImg from '@/assets/dare_2_drop.jpg';
import spacexImg from '@/assets/spacex.jpg';
import dinoImg from '@/assets/dino_splashdown.jpg';
import splashAhoyImg from '@/assets/splash_ahoy.jpg';
import cinema360Img from '@/assets/cinema_360.jpg';
import chaiSpinImg from '@/assets/chai_spin_chaos.jpg';
import alibabaImg from '@/assets/alibaba.jpg';
import bhangarhImg from '@/assets/bhangarh.jpg';
import wrathImg from '@/assets/wrath_of_the_gods.jpg';
import miniFallImg from '@/assets/mini_fall.jpg';
import carouselImg from '@/assets/magic_carousel.jpg';
import chhotaBheemImg from '@/assets/chhota_bheem.jpg';
import goldRushImg from '@/assets/gold_rush_express.jpg';
import castleImg from '@/assets/thrillverse-castle.jpg';

export type LocationType = 'ride' | 'restaurant' | 'facility' | 'event' | 'zone' | 'entrance';

export interface ParkLocation {
  id: string;
  name: string;
  type: LocationType;
  emoji?: string;
  category?: RideCategory | string;
  thrillLevel?: ThrillLevel;
  heightReq?: number;
  duration?: string;
  capacity?: string;
  status: 'open' | 'closed' | 'maintenance';
  waitTime?: number;
  coords: [number, number]; // [y, x] in 1024x682 CRS.Simple space
  description: string;
  image: string;
  zoneId: 'thriller' | 'water' | 'family' | 'kids' | 'entrance' | 'center';
  zoneName: string;
  hasVirtualQueue?: boolean;
  virtualQueueStatus?: string;
}

export const PARK_ZONES = [
  { id: 'all', name: 'All Zones', color: 'bg-slate-800 text-white' },
  { id: 'thriller', name: 'Thriller Zone', color: 'bg-red-500 text-white' },
  { id: 'water', name: 'Water Zone', color: 'bg-blue-500 text-white' },
  { id: 'family', name: 'Family Zone', color: 'bg-emerald-500 text-white' },
  { id: 'kids', name: 'Kids Zone', color: 'bg-amber-500 text-white' },
  { id: 'entrance', name: 'Main Entrance & Plaza', color: 'bg-purple-500 text-white' },
];

export const PARK_LOCATIONS: ParkLocation[] = [
  // ---------------- THRILLER ZONE ----------------
  {
    id: 'r-nitro',
    name: '1 Nitro',
    type: 'ride',
    emoji: '🎢',
    category: 'Roller Coaster',
    thrillLevel: 'Extreme',
    heightReq: 130,
    duration: '2.5 mins',
    capacity: '24 riders / train (1400/hr)',
    status: 'open',
    waitTime: 45,
    coords: [580, 200],
    description: "India's highest and fastest floorless roller coaster featuring 5 thrilling inversions and a 142ft drop at 105 km/h.",
    image: nitroImg,
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Open (Next slot: 11:15 AM)',
  },
  {
    id: 'r-scream',
    name: '2 Scream Machine',
    type: 'ride',
    emoji: '🎡',
    category: 'Extreme Pendulum',
    thrillLevel: 'Extreme',
    heightReq: 135,
    duration: '2.0 mins',
    capacity: '40 riders / cycle (800/hr)',
    status: 'open',
    waitTime: 35,
    coords: [510, 105],
    description: 'A massive rotating pendulum that swings riders up to 148 feet in the air at 360-degree angles.',
    image: screamImg,
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Open (Next slot: 11:30 AM)',
  },
  {
    id: 'r-spacex',
    name: '3 SpaceX',
    type: 'ride',
    emoji: '🚀',
    category: 'Indoor Launch Coaster',
    thrillLevel: 'Extreme',
    heightReq: 125,
    duration: '1.8 mins',
    capacity: '16 riders / train (1100/hr)',
    status: 'open',
    waitTime: 30,
    coords: [480, 240],
    description: 'High-speed indoor dark coaster launching riders into deep space with futuristic visual light projections.',
    image: spacexImg,
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Open (Next slot: 11:05 AM)',
  },
  {
    id: 'r-drop',
    name: '4 Dare 2 Drop',
    type: 'ride',
    emoji: '🪂',
    category: 'Drop Tower',
    thrillLevel: 'Extreme',
    heightReq: 120,
    duration: '1.5 mins',
    capacity: '12 riders / drop (600/hr)',
    status: 'open',
    waitTime: 40,
    coords: [545, 345],
    description: 'Shoots riders 132 feet straight into the sky before experiencing a zero-gravity freefall drop back down.',
    image: dropImg,
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Open (Next slot: 11:45 AM)',
  },

  // ---------------- WATER ZONE ----------------
  {
    id: 'r-dino',
    name: '5 Dino Splashdown',
    type: 'ride',
    emoji: '🦕',
    category: 'Water Flume',
    thrillLevel: 'Adventure',
    heightReq: 110,
    duration: '4.0 mins',
    capacity: '20 riders / boat (1000/hr)',
    status: 'open',
    waitTime: 25,
    coords: [585, 660],
    description: 'A prehistoric water safari through animatronic dinosaur jungle habitats climaxing in a 50ft splash drop.',
    image: dinoImg,
    zoneId: 'water',
    zoneName: 'Water Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Open (Next slot: 11:20 AM)',
  },
  {
    id: 'r-ahoy',
    name: '6 Splash Ahoy!',
    type: 'ride',
    emoji: '💦',
    category: 'Interactive Water Battle',
    thrillLevel: 'Family',
    heightReq: 100,
    duration: '4.5 mins',
    capacity: '8 riders / ship (700/hr)',
    status: 'open',
    waitTime: 20,
    coords: [490, 830],
    description: 'Pirate ship water battle where guests operate mounted water cannons targeting rival ships and shore targets.',
    image: splashAhoyImg,
    zoneId: 'water',
    zoneName: 'Water Zone',
    hasVirtualQueue: true,
    virtualQueueStatus: 'Available',
  },

  // ---------------- FAMILY ZONE ----------------
  {
    id: 'r-gold',
    name: '7 Gold Rush Express',
    type: 'ride',
    emoji: '🚂',
    category: 'Family Mine Coaster',
    thrillLevel: 'Adventure',
    heightReq: 95,
    duration: '3.0 mins',
    capacity: '30 riders / train (1200/hr)',
    status: 'open',
    waitTime: 15,
    coords: [360, 110],
    description: 'Wild west mining train coaster whipping through canyons, abandoned mine shafts, and wooden trestle bridges.',
    image: goldRushImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-alibaba',
    name: '8 Alibaba aur Chalis Chorr',
    type: 'ride',
    emoji: '🕌',
    category: 'Interactive Dark Ride',
    thrillLevel: 'Family',
    heightReq: 80,
    duration: '6.0 mins',
    capacity: '4 riders / car (900/hr)',
    status: 'open',
    waitTime: 20,
    coords: [345, 245],
    description: 'Interactive laser-shooting dark ride set in ancient Arabia to defeat forty thieves and unlock treasure vaults.',
    image: alibabaImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-bhangarh',
    name: '9 Bhangarh: The Curse',
    type: 'ride',
    emoji: '👻',
    category: 'Haunted Dark Ride',
    thrillLevel: 'Adventure',
    heightReq: 90,
    duration: '7.0 mins',
    capacity: '6 riders / vehicle (850/hr)',
    status: 'open',
    waitTime: 15,
    coords: [295, 280],
    description: 'Immersive spooky journey through haunted fort corridors featuring live actors, holographic ghosts, and spectral soundscapes.',
    image: bhangarhImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-chai',
    name: '10 Chai Spin Chaos',
    type: 'ride',
    emoji: '☕',
    category: 'Spinning Tea Cups',
    thrillLevel: 'Family',
    heightReq: 0,
    duration: '3.0 mins',
    capacity: '60 riders / cycle (900/hr)',
    status: 'open',
    waitTime: 10,
    coords: [230, 165],
    description: 'Whimsical spinning teacups with central steerable steering wheels on a turntable floor.',
    image: chaiSpinImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-wrath',
    name: '11 Wrath of the Gods',
    type: 'ride',
    emoji: '🔥',
    category: 'Walkthrough Show',
    thrillLevel: 'Adventure',
    heightReq: 90,
    duration: '12.0 mins',
    capacity: '150 guests / show (1500/hr)',
    status: 'open',
    waitTime: 25,
    coords: [170, 185],
    description: 'Live multi-sensory theatrical show showcasing ancient deity wrath with real fire bursts, water walls, and tumbling ruins.',
    image: wrathImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-carousel',
    name: '12 Magic Carousel',
    type: 'ride',
    emoji: '🎠',
    category: 'Grand Carousel',
    thrillLevel: 'Kids',
    heightReq: 0,
    duration: '4.0 mins',
    capacity: '72 riders / cycle (1000/hr)',
    status: 'open',
    waitTime: 5,
    coords: [195, 310],
    description: 'Double-decker handcrafted Victorian carousel with orchestral melodies and 60 jumping horses.',
    image: carouselImg,
    zoneId: 'family',
    zoneName: 'Family Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },

  // ---------------- KIDS ZONE ----------------
  {
    id: 'r-chhota',
    name: '13 Chhota Bheem – The Ride',
    type: 'ride',
    emoji: '👦',
    category: 'Kids Coaster',
    thrillLevel: 'Kids',
    heightReq: 0,
    duration: '2.5 mins',
    capacity: '16 kids / train (600/hr)',
    status: 'open',
    waitTime: 10,
    coords: [335, 785],
    description: 'Gentle family coaster themed around Dholakpur village with Bheem and his friends.',
    image: chhotaBheemImg,
    zoneId: 'kids',
    zoneName: 'Kids Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-minifall',
    name: '14 Mini Fall',
    type: 'ride',
    emoji: '⬇️',
    category: 'Junior Drop Tower',
    thrillLevel: 'Kids',
    heightReq: 80,
    duration: '2.0 mins',
    capacity: '10 riders / cycle (400/hr)',
    status: 'open',
    waitTime: 15,
    coords: [255, 755],
    description: 'Bouncy mini drop tower tailored for children to experience light vertical hops and giggles.',
    image: miniFallImg,
    zoneId: 'kids',
    zoneName: 'Kids Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },
  {
    id: 'r-cinema',
    name: '16 Cinema 360 – Prince of Dark Waters',
    type: 'ride',
    emoji: '🎬',
    category: '360 Dome Cinema',
    thrillLevel: 'Family',
    heightReq: 0,
    duration: '10.0 mins',
    capacity: '200 seats / screening (1200/hr)',
    status: 'open',
    waitTime: 10,
    coords: [205, 665],
    description: 'Panoramic 360-degree dome projection theater transporting audiences into deep ocean mythical realms.',
    image: cinema360Img,
    zoneId: 'kids',
    zoneName: 'Kids Zone',
    hasVirtualQueue: false,
    virtualQueueStatus: 'Standby Only',
  },

  // ---------------- LANDMARKS & CENTER ----------------
  {
    id: 'l-castle',
    name: 'ThrillVerse Castle',
    type: 'facility',
    emoji: '🏰',
    status: 'open',
    coords: [420, 512],
    description: 'The iconic centerpiece castle featuring royal balcony photo lookouts, souvenir galleries, and night laser shows.',
    image: castleImg,
    zoneId: 'center',
    zoneName: 'Castle Plaza',
  },
  {
    id: 'l-lake',
    name: 'Crystal Lake',
    type: 'facility',
    emoji: '🏞️',
    status: 'open',
    coords: [310, 512],
    description: 'Scenic central lake with dancing fountain choreography, pedal boat rentals, and waterfront promenade.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600',
    zoneId: 'center',
    zoneName: 'Castle Plaza',
  },

  // ---------------- ENTRANCE & FACILITIES ----------------
  {
    id: 'l-entrance',
    name: 'Main Entrance Gate',
    type: 'entrance',
    emoji: '🚪',
    status: 'open',
    coords: [120, 512],
    description: 'Grand entrance archway with turnstile turnings, ticket scanner security, and welcoming fanfare.',
    image: 'https://images.unsplash.com/photo-1574007557342-9988d5eebf5b?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },
  {
    id: 'f-ticket',
    name: 'Ticket Counter',
    type: 'facility',
    emoji: '🎟️',
    status: 'open',
    coords: [75, 275],
    description: 'Park admission ticketing, Express Pass upgrades, annual pass processing, and wristband issuance.',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },
  {
    id: 'f-services',
    name: 'Guest Services',
    type: 'facility',
    emoji: 'ℹ️',
    status: 'open',
    coords: [75, 355],
    description: 'Visitor information, accessibility accommodations, lost and found, stroller rentals, and VIP assistance.',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },
  {
    id: 'f-lockers',
    name: 'Lockers',
    type: 'facility',
    emoji: '🛅',
    status: 'open',
    coords: [75, 615],
    description: 'Keyless electronic rental lockers with PIN access for secure storage of bags and personal items.',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },
  {
    id: 'f-souvenir',
    name: 'Souvenir Shop',
    type: 'facility',
    emoji: '🛍️',
    status: 'open',
    coords: [75, 700],
    description: 'Flagship retail emporium featuring official ThrillVerse merchandise, plush toys, apparel, and gifts.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },
  {
    id: 'f-parking',
    name: 'Visitor Parking',
    type: 'facility',
    emoji: '🅿️',
    status: 'open',
    coords: [30, 512],
    description: 'Main multi-level guest parking lot with EV charging stations and tram shuttle service to Entrance Gate.',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'entrance',
    zoneName: 'Main Entrance & Plaza',
  },

  // ---- ZONE FACILITIES ----
  {
    id: 'f-thriller-merch',
    name: 'Thriller Merch Shop',
    type: 'facility',
    emoji: '👕',
    status: 'open',
    coords: [630, 415],
    description: 'High-adrenaline extreme gear store with Nitro tees, action jackets, and ride memorabilia.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=600',
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
  },
  {
    id: 'f-photo-thriller',
    name: 'Photo Spot - Thriller Zone',
    type: 'facility',
    emoji: '📸',
    status: 'open',
    coords: [520, 320],
    description: 'Dedicated photo vantage point with ThrillVerse backdrop framing Nitro and Dare 2 Drop towers.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600',
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
  },
  {
    id: 'f-washroom-thriller',
    name: 'Washrooms - Thriller Zone',
    type: 'facility',
    emoji: '🚻',
    status: 'open',
    coords: [470, 45],
    description: 'Clean air-conditioned restrooms with baby diaper changing stations and water refill kiosks.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'thriller',
    zoneName: 'Thriller Zone',
  },

  {
    id: 'f-washroom-water',
    name: 'Washrooms - Water Zone',
    type: 'facility',
    emoji: '🚻',
    status: 'open',
    coords: [635, 840],
    description: 'Water zone changing facilities, lockers, hot showers, and restrooms.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'water',
    zoneName: 'Water Zone',
  },
  {
    id: 'f-food-water',
    name: 'Food Court - Water Zone',
    type: 'restaurant',
    emoji: '🍕',
    status: 'open',
    coords: [590, 915],
    description: 'Tropical oasis food hall offering seafood baskets, gourmet wood-fired pizza, and iced drinks.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=600',
    zoneId: 'water',
    zoneName: 'Water Zone',
  },
  {
    id: 'f-aid-water',
    name: 'First Aid - Water Zone',
    type: 'facility',
    emoji: '⛑️',
    status: 'open',
    coords: [530, 955],
    description: 'Full-service medical station staffed by paramedics with emergency care and heat relief services.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=600',
    zoneId: 'water',
    zoneName: 'Water Zone',
  },
  {
    id: 'f-shop-water',
    name: 'Shop - Water Zone',
    type: 'facility',
    emoji: '🕶️',
    status: 'open',
    coords: [460, 705],
    description: 'Water adventure store with swimwear, sunblock, towels, waterproof phone pouches, and sandals.',
    image: 'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&q=80&w=600',
    zoneId: 'water',
    zoneName: 'Water Zone',
  },

  {
    id: 'f-restaurant-family',
    name: 'Restaurant - Family Zone',
    type: 'restaurant',
    emoji: '🍔',
    status: 'open',
    coords: [280, 55],
    description: 'Spacious family diner serving artisan burgers, frankfurters, crispy fries, milkshakes, and salads.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600',
    zoneId: 'family',
    zoneName: 'Family Zone',
  },
  {
    id: 'f-washroom-family',
    name: 'Washrooms - Family Zone',
    type: 'facility',
    emoji: '🚻',
    status: 'open',
    coords: [190, 40],
    description: 'Family-friendly restrooms with private nursing rooms and child-height washbasins.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'family',
    zoneName: 'Family Zone',
  },
  {
    id: 'f-shop-family',
    name: 'Shop - Family Zone',
    type: 'facility',
    emoji: '🎁',
    status: 'open',
    coords: [180, 70],
    description: 'Handicraft bazaar selling traditional toys, themed candy, and souvenir trinkets.',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'family',
    zoneName: 'Family Zone',
  },

  {
    id: 'f-washroom-kids',
    name: 'Washrooms - Kids Zone',
    type: 'facility',
    emoji: '🚻',
    status: 'open',
    coords: [365, 930],
    description: 'Kids zone restrooms equipped with toddler changing pads and cheerful colorful interiors.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    zoneId: 'kids',
    zoneName: 'Kids Zone',
  },
  {
    id: 'f-food-kids',
    name: 'Food Court - Kids Zone',
    type: 'restaurant',
    emoji: '🍦',
    status: 'open',
    coords: [305, 945],
    description: 'Colorful snack bar serving soft-serve ice cream, cotton candy, fresh popcorn, and fruit juices.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&q=80&w=600',
    zoneId: 'kids',
    zoneName: 'Kids Zone',
  },
  {
    id: 'f-photo-kids',
    name: 'Photo Spot - Kids Zone',
    type: 'facility',
    emoji: '📸',
    status: 'open',
    coords: [245, 960],
    description: 'Character meet-and-greet photo spot featuring Chhota Bheem statue installations.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600',
    zoneId: 'kids',
    zoneName: 'Kids Zone',
  },
  {
    id: 'f-aid-kids',
    name: 'First Aid - Kids Zone',
    type: 'facility',
    emoji: '⛑️',
    status: 'open',
    coords: [190, 950],
    description: 'Pediatric first-aid station with nursing care, lost child reunification area, and quiet room.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=600',
    zoneId: 'kids',
    zoneName: 'Kids Zone',
  },
  {
    id: 'f-shop-kids',
    name: 'Shop - Kids Zone',
    type: 'facility',
    emoji: '🧸',
    status: 'open',
    coords: [140, 930],
    description: 'Toy store packed with character costumes, bubble wands, action figures, and plushies.',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&q=80&w=600',
    zoneId: 'kids',
    zoneName: 'Kids Zone',
  },
];
